title: Johann Becker # your name (or website title) here
logo: "/images/scuba.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Masters Student
  URI <a href="https://web.uri.edu/engineering/about/ocean-engineering/">Department of Ocean Engineering</a>
  Narragansett, RI 02882
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
